version: '3'

services:

  app:
    container_name: boryspil_express_api
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  mongo:
    container_name: boryspil_express_db
    build: .docker/mongo/Dockerfile
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/mongo_config:/data/configdb
    ports:
      - "27017:27017"
    restart: unless-stopped