version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      PORT: ${PORT}