version: '3'

services:

  app:
    container_name: boryspil_express_api
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  mongo:
    container_name: boryspil_express_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITBD_DATABASE: boryspil_db
    volumes:
      - .docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - .docker/mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped