version: '3'

services:

  app:
    container_name: boryspil_express_api
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  mongo:
    container_name: boryspil_express_db
    build: .docker/mongo/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITBD_DATABASE: boryspil_db
    volumes:
      - .docker/mongo/mongod.conf:/etc/mongod.conf
      - .docker/mongo/initdb.d:/docker-entrypoint-initdb.d
      - .docker/mongo:/data/db
      - .docker/mongo/log/:/var/log/mongodb/
    ports:
      - "27017:27017"
    restart: unless-stopped