version: '3'

services:

  app:
    build:
      env_file:
        - .env
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      PORT: ${PORT}