version: '3'

services:

  app:
    container_name: boryspil_express_api
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  mongo:
    container_name: boryspil_express_mongo
    image: mongo:latest
    environment:
      MONGODB_USER: "${MONGO_USER}"
      MONGODB_DATABASE: "${DATABASE}"
      MONGODB_PASS: "${MONGO_PASSWORD}"
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    volumes:
      - .docker/mongo:/data/db
    restart: unless-stopped